import { FileText, Lock, Search, Server, ShieldAlert, User } from 'lucide-react'
import { useRepositoryAnalysis } from '../contexts/RepositoryAnalysisContext'
import { EmptyState, LoadingState } from '../components/shared/StatusPanels'

export function Audit() {
  const { data, status } = useRepositoryAnalysis()
  if (status === 'analyzing') return <LoadingState title="Preparing audit workspace" hint="Waiting for repository analysis to complete" />
  if (!data) return <EmptyState title="Connect a repository to inspect audit context" description="Audit events require an organization or source-control provider. This workspace will retain filters and evidence when the contract is connected." icon={ShieldAlert} />

  const categories = [{ label: 'Security & access', icon: Lock, color: 'text-red-400' }, { label: 'Administrative actions', icon: User, color: 'text-sky-400' }, { label: 'System events', icon: Server, color: 'text-amber-400' }, { label: 'Repository evidence', icon: FileText, color: 'text-emerald-400' }]

  return <div className="space-y-5"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex items-center gap-3"><ShieldAlert className="size-5 text-amber-400" aria-hidden="true" /><h1 className="text-lg font-semibold text-white">Audit Logs</h1></div><p className="mt-1 text-xs text-zinc-500">Evidence and access history for {data.repository.owner}/{data.repository.name}.</p></div><span className="neo-pressed px-3 py-2 text-[10px] text-zinc-500">Audit provider not configured</span></header><div className="grid gap-5 lg:grid-cols-[220px_minmax(0,1fr)]"><aside className="neo-flat p-4"><h2 className="text-xs font-semibold uppercase tracking-wider text-zinc-400">Event types</h2><div className="mt-4 space-y-3">{categories.map(({ label, icon: Icon, color }) => <label key={label} className="flex items-center gap-2 text-xs text-zinc-500"><input type="checkbox" disabled defaultChecked className="accent-amber-500" /><Icon className={`size-3.5 ${color}`} aria-hidden="true" />{label}</label>)}</div></aside><section className="neo-flat min-h-[360px] overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-zinc-800/70 p-4"><h2 className="text-sm font-medium text-zinc-200">Repository audit trail</h2><div className="neo-pressed flex items-center gap-2 px-3 py-2 text-xs text-zinc-600"><Search className="size-3.5" aria-hidden="true" />Search unavailable</div></div><div className="flex min-h-[280px] items-center justify-center p-8 text-center"><div><FileText className="mx-auto size-7 text-zinc-700" aria-hidden="true" /><p className="mt-3 text-sm text-zinc-400">No audit events available</p><p className="mt-1 max-w-md text-xs leading-5 text-zinc-600">The selected snapshot was analyzed successfully, but audit history is owned by the organization and source-control integrations.</p></div></div></section></div></div>
}
