import { Building2, CreditCard, Mail, Settings, Shield, Users } from 'lucide-react'
import { useRepositoryAnalysis } from '../contexts/RepositoryAnalysisContext'
import { ErrorState, LoadingState } from '../components/shared/StatusPanels'

const areas = [{ label: 'Team management', icon: Users }, { label: 'Security & access', icon: Shield }, { label: 'Billing & usage', icon: CreditCard }, { label: 'Workspace settings', icon: Settings }]

export function Organizations() {
  const { data, error, status } = useRepositoryAnalysis()
  if (status === 'analyzing') return <LoadingState title="Preparing organization workspace" hint="Waiting for repository context" />

  return <div className="space-y-5">{error && <ErrorState title="Organization context unavailable" description={error} />}<header><div className="flex items-center gap-3"><Building2 className="size-5 text-sky-400" aria-hidden="true" /><h1 className="text-lg font-semibold text-white">Organizations</h1></div><p className="mt-1 text-xs text-zinc-500">Workspace access, teams, billing, and policy controls.</p></header><div className="grid gap-5 lg:grid-cols-[220px_minmax(0,1fr)]"><aside className="neo-flat p-3"><div className="space-y-1">{areas.map(({ label, icon: Icon }, index) => <button type="button" disabled key={label} className={`flex w-full items-center gap-3 px-3 py-2.5 text-left text-xs ${index === 0 ? 'neo-pressed text-sky-400' : 'text-zinc-600'}`}><Icon className="size-3.5" aria-hidden="true" />{label}</button>)}</div></aside><section className="space-y-5"><div className="neo-flat p-5"><div className="flex items-center gap-2 border-b border-zinc-800/70 pb-4"><Users className="size-4 text-sky-400" aria-hidden="true" /><h2 className="text-sm font-medium text-zinc-200">Teams</h2></div><div className="flex min-h-36 items-center justify-center text-center"><div><p className="text-sm text-zinc-400">No organization data connected</p><p className="mt-1 max-w-sm text-xs leading-5 text-zinc-600">Team membership, roles, and invitations will be loaded from the organization provider. {data ? `The current repository belongs to ${data.repository.owner}.` : 'Connect a repository or organization to continue.'}</p></div></div></div><div className="neo-flat p-5"><div className="flex items-center gap-2 border-b border-zinc-800/70 pb-4"><Mail className="size-4 text-amber-400" aria-hidden="true" /><h2 className="text-sm font-medium text-zinc-200">Invitations</h2></div><p className="py-8 text-center text-xs text-zinc-600">Pending invitations will appear when an organization provider is configured.</p></div></section></div></div>
}
