import { Folder, GitBranch, Plus, Search, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useRepositoryAnalysis } from '../contexts/RepositoryAnalysisContext'
import { EmptyState, LoadingState } from '../components/shared/StatusPanels'

export function Projects() {
  const { data, status } = useRepositoryAnalysis()
  const [search, setSearch] = useState('')
  if (status === 'analyzing') return <LoadingState title="Preparing project workspace" hint="Waiting for repository analysis" />

  return <div className="space-y-5"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex items-center gap-3"><Folder className="size-5 text-amber-400" aria-hidden="true" /><h1 className="text-lg font-semibold text-white">Projects</h1></div><p className="mt-1 text-xs text-zinc-500">Group repositories into durable workspaces for health, planning, and delivery.</p></div><button type="button" disabled className="neo-accent inline-flex items-center gap-2 px-3 py-2 text-xs opacity-40"><Plus className="size-3.5" aria-hidden="true" />New project</button></header><div className="neo-pressed flex items-center gap-2 px-3"><Search className="size-4 text-zinc-600" aria-hidden="true" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search projects" className="h-10 w-full bg-transparent text-sm text-white outline-none placeholder:text-zinc-600" /><span className="text-[10px] text-zinc-700">{search ? 'Local filter' : 'Provider required'}</span></div>{data ? <section className="neo-flat p-5"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><GitBranch className="size-4 text-sky-400" aria-hidden="true" /><h2 className="text-sm font-medium text-zinc-200">Current repository workspace</h2></div><p className="mt-2 text-lg font-semibold text-zinc-100">{data.repository.owner}/{data.repository.name}</p><p className="mt-1 text-xs text-zinc-500">{data.repository.branch} · {data.repository.files.toLocaleString()} files · {data.repository.lines_of_code.toLocaleString()} lines</p></div><ShieldCheck className="size-5 text-emerald-400" aria-hidden="true" /></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Detail label="Health" value={`${data.health.score}/100`} /><Detail label="Language" value={data.repository.primary_language || 'Not detected'} /><Detail label="Risks" value={`${data.risks.critical.length + data.risks.warnings.length}`} /></div><Link to="/repository" className="mt-5 inline-flex text-xs text-amber-400 hover:text-amber-300">Open repository overview →</Link></section> : <EmptyState title="No project provider connected" description="Project records, membership, and activity will appear here when the workspace contract is available. Analyze a repository to preview its project-level signals." icon={Folder} />}</div>
}

function Detail({ label, value }: { label: string; value: string }) { return <div className="neo-pressed p-3"><p className="text-[10px] uppercase tracking-wider text-zinc-600">{label}</p><p className="mt-2 text-sm text-zinc-300">{value}</p></div> }
